# Copyright (c) 2019 3MF Consortium
# All rights reserved.

# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:

# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Configuration file for Travis CI (https://travis-ci.org)
#
# It is used to create am easily distributable and printable PDF
# version of a specification document written in markdown (3MF-style).
# 
# Each commit to this repository will trigger a build of this repository on https://travis-ci.org .
# If this commit was performed on master, a new draft of a release that contains
# the generated PDF as artifact will be created on the releases page of this repo.
# You can
# 1. discard it
# 2. modify it to become a proper release of this specification or
# 3. take the PDF and use it in a different release.

# How to get this setup working:
# 1. register on https://travis-ci.org
# 2. On https://travis-ci.org "sync" the "3MF Consortium" organization
# 3. add a personal github access token to your account: https://github.com/settings/tokens
# 4. enable this repo to be built and add an env-variable with name "GITHUB_API_KEY" and your access token as value.
# 5. Tigger a build on https://travis-ci.org or commit to "master" to automatically start a build
# => On success a new release with the PDF as artifact should have been created.


dist: xenial
language: python
python: 3.7

env:
  - SPECNAME="3MF Beam Lattice Extension"
install:
  - pip install grip
  - ./mdToPDF/install_wkhtmltopdf.sh

script:
  - ./mdToPDF/mdToPDF.sh "$SPECNAME"
  
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: '${SPECNAME}.pdf'
  skip_cleanup: true
  draft: true
  name: "Snapshot"
  body: "This is an autogenerated PDF version of $SPECNAME."
  prerelease: true
  on:
    branch: master
